### ISSUE TITLE
Centos 6.5  PHP5.6 curl 经常卡住

### ISSUE THREAD

**Issue by zhqagp** [osgochina/swoole-crontab#13]
在本机执行 curl  http://127.0.0.1:9501/conf 经常会卡住。

**Comment by zhqagp** [comment]
<img width="674" alt="qq20150930-1 2x" src="https://cloud.githubusercontent.com/assets/6457312/10182985/4d47ee30-675d-11e5-860e-a3ec8371af67.png">

**Comment by osgochina** [comment]
CURL在发送较大的POST请求时会先发一个100-continue的请求，如果收到服务器的回应才会发送实际的POST数据。而swoole_http_server不支持100-continue，就会导致CURL请求超时。

解决办法是关闭CURL的100-continue

http://wiki.swoole.com/wiki/page/433.html
