### ISSUE TITLE
任务方式以文件获取的话，增加任务如何做比较好

### ISSUE THREAD

**Issue by luashiping** [osgochina/swoole-crontab#16]
现在我的项目打算以文件的方式添加任务，也就是要修改crontab.php文件。这样子感觉太麻烦了，修改完后每次还要php调shell命令去reload配置文件！有什么好的办法吗？

**Comment by osgochina** [comment]
目前的模式的没一分钟会自动重新载入配置文件，如果你的业务精确到秒，需要手动reload，如果精确到分钟，可以直接修改文件，一分钟后自动会载入
