### ISSUE TITLE
执行差不多几周，就会出现假死，用检查是否存在进程的命令提示是正在运行，其实已经成了僵尸进程了，需要执行重启命令才会可以

### ISSUE THREAD

**Issue by x-bean** [osgochina/swoole-crontab#20]

**Comment by osgochina** [comment]
能查看一下lsof -p 进程id 看看连接数。
还有看下cpu和内存的占用情况，如果能有strace文件就最好

**Comment by ouminghai** [comment]
我也有同样的情况，大概运行25天主进程就会挂掉。主进程显示不是僵死进程。并且不再去读任务列表，也就是说 定时器不再运作

**Comment by osgochina** [comment]
好的，我跟rango提下这个问题

**Comment by osgochina** [comment]
版本和环境能提供一下吗？

**Comment by ouminghai** [comment]
php 5.4 centos 6.5

**Comment by x-bean** [comment]
centos6.5

在 2016-01-31 09:40:51，"ClownFish" notifications@github.com 写道：

版本和环境能提供一下吗？

**Comment by osgochina** [comment]
这个bug是swoole的定时器bug，定时器是int32位的，执行到20多天，溢出变成0了。
swoole已经修复，建议升级到swoole 1.7.22+

**Comment by x-bean** [comment]
谢谢

在 2016-02-01 12:46:50，"ClownFish" notifications@github.com 写道：

这个bug是swoole的定时器bug，定时器是int32位的，执行到20多天，溢出变成0了。
swoole已经修复，建议升级到swoole 1.7.22+
