### ISSUE TITLE
mac 10.11.3 有  cli_set_process_title 错误提示呢

### ISSUE THREAD

**Issue by lyf845990516** [osgochina/swoole-crontab#21]
PHP Warning:  cli_set_process_title(): cli_set_process_title had an error: Not initialized correctly in /Users/liuyunfei/swoole-crontab/src/include/Process.class.php on line 50

**Comment by osgochina** [comment]
这是mac下swoole的支持问题，请无视它。目前swoole没有明确的支持时间。

**Comment by jianingguo** [comment]
也遇到了同样的问题

**Comment by shuliangfu** [comment]
mac os 不支持修改进程名称，判断一下，如果是mac os系统就不用设置进程名称了

**Comment by osgochina** [comment]
@shuliangfu 你升级最新版本的swoole framework  我已经从框架层面修改了,
