### ISSUE TITLE
v1.0版本设置"并发任务数"不起作用 + 同一个分组的agent不能同时执行相同的任务

### ISSUE THREAD

**Issue by forgottener** [osgochina/swoole-crontab#27]
![clipboard](https://cloud.githubusercontent.com/assets/8578113/19685563/e360c1e6-9aef-11e6-9fe3-412947691fef.png)

![20161025201802](https://cloud.githubusercontent.com/assets/8578113/19685641/34edf5d8-9af0-11e6-9bd6-ecaf8c636481.png)

**Comment by osgochina** [comment]
并发任务数是个bug，已经修复，请查看我最新版本。

**Comment by forgottener** [comment]
并发任务数的意思是同一时间执行这个脚本多少次,还是说是swoole的并发? 我测了下还是只执行了一次,难道我理解错了,这个不是执行多少次的设置?

**Comment by forgottener** [comment]
参考作者的方法,我自己写了个项目满足了多开进程和多台agent的实现;
https://github.com/forgottener/swoole-crontab-process
