### ISSUE TITLE
安装好后的默认的测试任务没能执行

### ISSUE THREAD

**Issue by waynesun01** [osgochina/swoole-crontab#36]
任务日志显示“任务发送失败”；同时php_error.log中显示：
PHP Warning:  Swoole\Database\MySQLi SQL Error:Commands out of sync; you can't run this command now<hr />insert into `term_logs` (`taskid`,`runid`,`explain`,`msg`,`createtime`) values('3097968986801831941','3112807076871536715','任务开始','{\"id\":3097968986801831941,\"execute\":\"\\/bin\\/echo &#039;hello swoole-crontab&#039; &gt;&gt; \\/home\\/wwwlogs\\/crontab.log\",\"agents\":\"1\",\"taskname\":\"\\u6d4b\\u8bd5\\u4efb\\u52a1\",\"runuser\":\"nobody\",\"runid\":3112807076871536715}','2017-01-13 18:08:59')<hr />
Server: localhost:3306. <br/>
另：求该项目的架构图及实现流程
多谢

**Comment by osgochina** [comment]
已经修复以上问题,
