### ISSUE TITLE
agent 出现swoole_table::set(): Unable to allocate memory

### ISSUE THREAD

**Issue by zhp1254** [osgochina/swoole-crontab#37]
阿里云运行一下午，晚上开始出现大量swoole_table::set(): Unable to allocate memory ；任务停止执行
运行命令 echo '123';sleep 60
机器内存4G,截止发帖时间，剩余内存1G,错误还在继续

**Comment by osgochina** [comment]
php版本，swoole版本，crontab版本。还是任务频率告诉下我。这个问题以前碰到过，应该修复了

**Comment by zhp1254** [comment]
PHP 5.6.24 swoole  1.9.6  
crontab   URL: https://github.com/osgochina/swoole-crontab.git 昨天更新到最新master分支
任务频率 10秒一次 并发数限制10

**Comment by zhp1254** [comment]
其它问题
1、创建任务0~59秒 每10秒执行 结果是一分钟执行一次，改成1~59就是每10秒一次
2、偶而出现 WARNING swSignalfd_onSignal: signal[1] callback is null
3、tasks通知中心服失败,code8002,msg
4、工作进程限制10，但是进行中的任务数每次都是12

**Comment by osgochina** [comment]
首先，这种情况是因为默认分配的共享内存不足造成的，我默认分配了1024个任务，也就是说最多能有1024个任务在运行。你现在这种情况应该是开启了任务没有正常结束，占用了任务数量内存没有释放。
不建议使用echo '123';sleep 60这种连续命令，多命令请放到一个shell脚本中执行

**Comment by zhp1254** [comment]
1、一个任务做1分钟，1-59每10秒一个任务，一分钟5个任务并且限制了10个工作 进程，这种状况下肯定达到同时1024个任务；
2、swoole_process->exec支持多命令，且echo '123';sleep 60这种命令应该比较稳定，非正常结束的可以性比较小

**Comment by osgochina** [comment]
请把你的crontab 定时格式贴出来，我在我本机运行下

**Comment by zhp1254** [comment]
/bin/sh -c echo '123456789'>>/tmp/swoole.log;sleep 60
Process.php有修改
public function run($worker)
    {
        foreach (self::$process_list as $p){
            unset($p);
        }
        $exec = $this->task["execute"];
        $worker->name($this->task["taskname"] ."#". $this->task["id"]);

        $exec = explode(" ",trim($exec), 2);

        $execfile = array_shift($exec);
        if (!self::changeUser($this->task["runuser"])){
            echo "修改运行时用户失败\n";
            exit(101);
        }

        //命令带option参数
        if(count($exec) == 1){
           $tmp = trim($exec[0]);
           $tmp = htmlspecialchars_decode($tmp, ENT_QUOTES);
           if(strpos($tmp, '-') === 0){
                $exec = explode(" ", $tmp, 2);
           }
        }
        var_dump($exec);

        $worker->exec($execfile,$exec);
    }

**Comment by zhp1254** [comment]
还有什么时候出个流程图啊
CenterServer的工作流程确实没搞懂。。
onPipeMessage里GET_TASKS的woker没找到谁触发的
GET_TASKS后MANAGER_TASKS也没明白通知谁去了

**Comment by osgochina** [comment]
抱歉，我完全按照你说的方式测试，完全不能重现你的问题。但是你的代码里面有个问题。请使用
 public function run($worker)
    {
        foreach (self::$process_list as $p){
            $p->close();
        }
        self::$process_list = []; 这种方式释放句柄。你看看我Process.php文件的56行，句柄需要close，你那边更新了吗，这个问题只会造成句柄数一直增长，也不会造成内存爆掉

**Comment by osgochina** [comment]
跟这个问题相关的配置变量是const ROBOT_MAX_PROCESS = 1024; 决定了你最大能开启多少个任务

**Comment by zhp1254** [comment]
刚pull了下确实有更新 我今天再试下吧看明天会不会出现
还有个问题：
Process类144行，  $worker->name($exec ."#". $this->task["id"]);变量$exec长点会抛异常，提示应该是参数长度应该小于126
