### ISSUE TITLE
无法正常使用

### ISSUE THREAD

**Issue by blocksky** [osgochina/swoole-crontab#39]
你好，为什么我配置完了，只能显示权限和用户页面，其他页面都无法正常显示。 报错如下：
__construct

need a param of total

----------------------------------------------------------------------------------------------------
#0 line:54 call:Swoole\Error::info	file:/opt/tony/data/www/public/framework/libs/Swoole/Pager.php
#1 line:34 call:Swoole\Pager->__construct	file:/opt/tony/data/www/wwwroot/swoole-crontab-master/src/admin/controllers/Agent.php
#2 line:761 call:App\Controller\Agent->index	file:/opt/tony/data/www/public/framework/libs/Swoole/Swoole.php
#3 line:50 call:Swoole->runMVC	file:/opt/tony/data/www/wwwroot/swoole-crontab-master/src/public/index.php
----------------------------------------------------------------------------------------------------

谁能帮忙看一下嘛 ？ 谢谢

**Comment by osgochina** [comment]
这是因为后台程序需要连接到Center中心服务，未连接上报这个错。你中心服启动了吗？如果启动了，看下配置正确吗

**Comment by osgochina** [comment]
![image](https://cloud.githubusercontent.com/assets/1379073/24576013/8d043882-16e6-11e7-9013-eec6d7cfe102.png)

第二个文件在center/_init.php 中
![image](https://cloud.githubusercontent.com/assets/1379073/24576015/91583b22-16e6-11e7-8928-9b249fda2505.png)
这两个配置应该是有问题。你注意启动监听的ip，我center在没有配置环境变量的时候监听的ip不是127，这是我公司的项目，有写细节没有修改。你把这个监听ip改下应该就好了。
