### ISSUE TITLE
5.3.3兼容性问题

### ISSUE THREAD

**Issue by chunhei2008** [osgochina/swoole-crontab#4]
你好，我在5.3.3上修改了PHP的语法兼容性上的问题之后，没有报错但是启动之后没有运行任务。

**Comment by osgochina** [comment]
swoole扩展只支持PHP5.3.10以上版本，请升级版本

**Comment by chunhei2008** [comment]
谢谢，我在官方看是要求5.3+没做细分版本说明，还以为只需要5.3 就行，您这个项目现在有在生产机使用吗，我最近有相关的需求，找了很多项目实现方法基本都是类似使用PHP的进程控制扩展来实现，您的实现是我测试中比较符合需求的，由于生产机器升级PHP版本存在风险，目前还在测试一些版本兼容性问题。

**Comment by osgochina** [comment]
我也正在测试，还没有到生产环境使用，不过测试下来没发现很大的问题，正在排期上线。这个项目还是比较简单的，你可以看看代码或者小范围的灰度使用，欢迎给我提bug。

**Comment by chunhei2008** [comment]
我觉得使用swoole扩展实现一个小的web页面提供web接口用来管理任务（添加、删除、停止、开启）、查看任务状态、查看日志就更好了，可以为做一个集群式的任务管理后台提供API支持

**Comment by osgochina** [comment]
感谢你提供的建议，这些确实是我后期需要完善的地方，晚上回家思考下怎么做
