### ISSUE TITLE
cronAgent /agent/index/ 管理报错

### ISSUE THREAD

**Issue by TravelThePath** [osgochina/swoole-crontab#42]
Warning: Invalid argument supplied for foreach() in swoole-crontab/src/admin/controllers/Agent.php on line 44
$ret = App\Service::getInstance()->call("Agent::getAgents",$gets,$page,$pagesize)->getResult(10);这个查询并没有返回["total"=>$pager->total,"rows"=>$list]而是返回空 agents表里有数据的。这是为什么呢？

**Comment by xufei100** [comment]
你可能没有启动 agent ，这里是远程调用不是直接访问数据库

**Comment by osgochina** [comment]
是没有启动中心服.看下我最新提交的架构图你就明白了
