### ISSUE TITLE
Undefined index

### ISSUE THREAD

**Issue by mia0x75** [osgochina/swoole-crontab#43]
2017/07/18 10:06:33 [error] 3082#0: *8 FastCGI sent in stderr: "PHP message: PHP Notice:  Undefined index: _gid in /opt/www/swoole-crontab/src/admin/classes/CommonController.php on line 37
PHP message: PHP Notice:  Undefined index: _gname in /opt/www/swoole-crontab/src/admin/classes/CommonController.php on line 38" while reading response header from upstream, client: 127.0.0.1, server: localhost, request: "GET /password/modifypassword/ HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "localhost:8900", referrer: "http://localhost:8900/user/index/"

2017/07/18 10:06:36 [error] 3082#0: *8 FastCGI sent in stderr: "PHP message: PHP Notice:  Undefined index: _gid in /opt/www/swoole-crontab/src/admin/classes/CommonController.php on line 37
PHP message: PHP Notice:  Undefined index: _gname in /opt/www/swoole-crontab/src/admin/classes/CommonController.php on line 38
PHP message: PHP Notice:  Undefined index: _gid in /opt/www/swoole-crontab/src/admin/controllers/Crontab.php on line 35
PHP message: PHP Warning:  Invalid argument supplied for foreach() in /opt/www/swoole-crontab/src/admin/controllers/Crontab.php on line 50
PHP message: PHP Notice:  Undefined index: _gid in /opt/www/swoole-crontab/src/admin/controllers/Crontab.php on line 41" while reading response header from upstream, client: 127.0.0.1, server: localhost, request: "GET /crontab/index/ HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "localhost:8900", referrer: "http://localhost:8900/password/modifypassword/"

**Comment by osgochina** [comment]
请启动中心服

**Comment by mia0x75** [comment]
这个服务已经启动了，而且是第一个启动的。

root     32000  0.0  0.2 732268 17908 ?        Ssl  09:50   0:00 CenterServer: master -host=127.0.0.1 -port=8901
root     32001  0.0  0.1 429148 13876 ?        S    09:50   0:00 CenterServer: manager
root     32006  0.0  0.2 414784 17016 ?        S    09:50   0:00 CenterServer: task
root     32007  0.0  0.2 414784 17088 ?        S    09:50   0:00 CenterServer: task
root     32008  0.0  0.1 414784 15416 ?        S    09:50   0:00 CenterServer: task
root     32009  0.0  0.1 414784 15332 ?        S    09:50   0:00 CenterServer: task
root     32010  0.0  0.2 431168 20868 ?        S    09:50   0:00 CenterServer: worker
root     32011  0.0  0.2 431168 20804 ?        S    09:50   0:00 CenterServer: worker
root     32012  0.0  0.2 431168 20996 ?        S    09:50   0:00 CenterServer: worker
root     32013  0.0  0.2 431168 20892 ?        S    09:50   0:00 CenterServer: worker

**Comment by mia0x75** [comment]
center.php 连数据库问题。另外 $env = get_cfg_var('env.name'); 这个env.name是在php.ini中的？

**Comment by osgochina** [comment]
没错,env.name=dev  写入php.ini

**Comment by mia0x75** [comment]
issue solved.
