### ISSUE TITLE
几处修正

### ISSUE THREAD

**Issue by NaiBox** [osgochina/swoole-crontab#45]
1，说明文档 fix center为center.php
地点：/path/to/php /path/to/src/center/**center**  start -d -h 127.0.0.1 -p 8901

2, sql文件 swoole-crontab/doc/crontab.sql
agents 表有四个字段，但是insert插入语句有五个字段值；
地点：INSERT INTO `agents` VALUES ('1', 'Crontab服务', '127.0.0.1', '8902', '0');

**Comment by osgochina** [comment]
谢谢提交bug,已经修复了
