### ISSUE TITLE
有错误

### ISSUE THREAD

**Issue by w3yyb** [osgochina/swoole-crontab#7]
PHP Fatal error:  Cannot use object of type swoole_http_response as array in  swoole-crontabv0.2/src/include/Http.class.php on line 50
，另外为什么 http://127.0.0.1:9501 ,第一次能访问，以后就不能访问 了

**Comment by osgochina** [comment]
麻烦你重新更新一下，我修正了bug，

**Comment by w3yyb** [comment]
好，谢谢
